In [45]:
import pandas as pd
from datetime import datetime, timedelta

df = pd.read_csv('../extrato.csv', sep=";")


df['Valor'] = df['Valor'].str.replace('.', '')
df['Valor'] = df['Valor'].str.replace(',', '.').astype(float)

df['Data Lançamento'] = pd.to_datetime(df['Data Lançamento'], format="%d/%m/%Y")

last_month_date = datetime.now() - timedelta(days=30)
df[
    (df['Descrição'].str.contains('Credito Evento B3'))
    & (df['Data Lançamento'] >= last_month_date)
    ]

,Data Lançamento,Descrição,Valor,Saldo
565,2025-03-25,"Credito Evento B3: ""* PROV * RENDIMENTO 11 ...",10.12,"35,79"
566,2025-03-25,"Credito Evento B3: ""* PROV * RENDIMENTO 2 ...",1.56,"37,35"
573,2025-04-01,"Credito Evento B3: ""* PROV * JUROS S/CAPITAL 3...",0.60,"12,95"
574,2025-04-01,"Credito Evento B3: ""* PROV * JUROS S/CAPITAL 3...",0.60,"13,55"
589,2025-04-07,"Credito Evento B3: ""* PROV * RENDIMENTO 8 ...",8.40,"344,76"
597,2025-04-11,"Credito Evento B3: ""* PROV * RENDIMENTO 20 ...",20.80,"159,65"
603,2025-04-14,"Credito Evento B3: ""* PROV * RENDIMENTO 9 ...",7.65,"-0,63"
604,2025-04-14,"Credito Evento B3: ""* PROV * RENDIMENTO 6 ...",6.60,"5,97"
605,2025-04-14,"Credito Evento B3: ""* PROV * RENDIMENTO 30 ...",2.76,"8,73"
606,2025-04-14,"Credito Evento B3: ""* PROV * RENDIMENTO 13 ...",10.66,"19,39"
607,2025-04-14,"Credito Evento B3: ""* PROV * RENDIMENTO 276 ...",24.84,"44,23"
614,2025-04-22,"Credito Evento B3: ""* PROV * DIVIDENDOS 30 ...",2.76,"97,47"

In [27]:
from datetime import date

print(date.today())

2025-04-22